import config from '@gasbuddy/coconfig';

// v23 web TS baseline: webpack+babel SSR React apps (NOT Next.js -- see designer-web,
// the pilot/adoption target). Type checking is `tsc --noEmit` only; the actual build is
// Babel (webpack client + `babel --extensions '.js,.jsx,.ts,.tsx'` server), which is why
// `noEmit` flips to true here even though the base (service) tsconfig emits.
Object.assign(config['tsconfig.json'].configuration, {
  include: ['src', 'tests', 'types', '.storybook'],
  exclude: ['node_modules', 'build', 'build-static'],
});

Object.assign(config['tsconfig.json'].configuration.compilerOptions, {
  moduleResolution: 'node',
  lib: ['ES2022', 'DOM', 'DOM.Iterable'],
  jsx: 'react-jsx',
  allowJs: true,
  checkJs: false,
  noEmit: true,
  resolveJsonModule: true,
  skipLibCheck: true,
  forceConsistentCasingInFileNames: true,
});

const eslint = config['.eslintrc.js'].configuration as any;

// Web apps own their own two-tier Jest setup (jsdom unit + node integration, babel-jest --
// see @gasbuddy/service-tester's webJestConfig), not the base's single ts-jest config.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const { 'jest.config.js': omittedBaseJestConfig, ...configWithoutJest } = config;

export default {
  ...configWithoutJest,
  '.eslintrc.js': {
    configuration: {
      ...eslint,
      extends: '@gasbuddy/eslint-config-gasbuddy-web',
      overrides: [
        ...(eslint.overrides || []),
        // F6/SC-13 fix: @gasbuddy/eslint-config-gasbuddy-web's own test/story override
        // only covers *.test.js(x) and *.stories.js(x) -- widen here so .ts/.tsx and
        // .spec.* variants get the same devDependencies/max-len relaxations.
        {
          files: ['**/*.{test,spec,stories}.{js,jsx,ts,tsx}'],
          rules: {
            'import/no-extraneous-dependencies': ['error', { devDependencies: true }],
            'max-len': 'off',
          },
        },
      ],
    },
  },
  // coconfig-generated files REPLACE app copies, and the base list is service-shaped.
  // Append the web build outputs so generated client bundles and storybook output
  // never get linted. Apps needing more entries extend via their own coconfig.ts.
  // (In the base package this entry is a plain string, not { configuration }.)
  '.eslintignore': `${config['.eslintignore'] as unknown as string}build-static/
storybook-static/
`,
  'types/web-globals.d.ts': {
    content: `/**
 * This file is generated by coconfig. Do not edit it directly.
 * Instead, edit the coconfig.js or coconfig.ts file in your project root.
 *
 * See https://github.com/gas-buddy/coconfig for more information.
 */

declare module '*.css' {
  const classes: Record<string, string>;
  export default classes;
}

declare module '*.svg' {
  const src: string;
  export default src;
}

declare module '*.png' {
  const src: string;
  export default src;
}

declare module '*.gif' {
  const src: string;
  export default src;
}

declare module '*.jpg' {
  const src: string;
  export default src;
}
`,
  },
};
